import sqlite3
conn=sqlite3.connect('bank-query-sf.db')
c=conn.cursor()
def create_table():
	c.execute("CREATE TABLE IF NOT EXISTS account_general_query(no_of_question REAL,query TEXT,answer TEXT)")

def data_entry(a,b,e):
	c.execute("INSERT INTO account_general_query VALUES(?,?,?)",(a,b,e))
	conn.commit()
	#c.close()
	#conn.close()

create_table()

data_entry(6, 'steps for opening an account || how do I open an account? || I want to open an account ||  want to open an account || open an account || new account open','Go to your nearest Sky-bits branch. Fill up Bank Account Opening Form. The proposal form must be duly filled in all respects. Necessary details regarding name, address, occupation and other details must be filled in wherever required. Two or three specimen signatures are required on the specimen signature card. If the account is opened in joint names, then the form must be signed jointly. You have to submit copies of his latest photograph for the purpose of his identification. Then submit Bank Account Opening Form and Documents. The duly filled in proposal form must be submitted to the bank along with necessary documents. For e.g. in case of a joint stock company, the application form must accompany with the Board\'s resolution to open the account. Also certified copies of articles and memorandum of association must be produced.')
data_entry(5, 'I want to close account || account close || how do I close my account || want to close my account || close an account','Go to your nearest Sky-bits branch. Fill up the account closure form which will be available at the bank, which can seek a reason for closure of account. The form should be signed by all account holders. Another form giving details of the account into which the balance funds can be transferred has to be filled. The account holders should personally visit the branch to carry out the closure. The bank may ask for unused cheque books and cards to be deposited along with the form. These documents and cards will be destroyed by the bank.')
data_entry(4, 'I want to update my contact information || How can I change my mobile number? || I want to change my address details ||  I want to change my mobile number ','There are many ways to update your contact details in your Sky-bits account:- a. If you have internet banking enabled in your account, you can login and update contact details by going to Options tab (on upper right side)->My profile(on left side). b. You can visit any nearest Sky-bits branch, fill out the contact details updation form and submit the form along with a copy of any one of the kyc documents to get your contact details updated.')
data_entry(1, 'minimum opening balance for a savings account','Customers holding regular savings accounts with our bank are required to maintain a monthly average balance to the tune of Rupees 1,000 - 3,000, which varies depending on branch location. For more details, go to http://sky-bits.com/')
data_entry(2, 'what are the documents required to open a Savings Account? || documents required to open a Savings Account','To open a savings account with our bank, customers will have to submit the following documents along with account opening form - a. Proof of identity - Passport, Driving license, Voter’s ID card, etc. b. Proof of address - Passport, Driving license, Voter’s ID card, etc. c. PAN card d. Form 16 (only if PAN card is not available) e. 2 latest passport size photographs')
data_entry(2, 'type of savings account || What are the various types of Savings accounts ?','mainly 3 types of savings account available - 1. Basic savings accounts, 2. Online savings accounts, 3. Money market accounts')
data_entry(1, 'What is savings Account?','A savings account is an interest-bearing deposit account held at a bank or other financial institution that provides a modest interest rate. Financial institutions that offer savings accounts may limit the number of withdrawals from an account each month. They also may charge fees unless you maintain a certain average monthly balance in the account. In most cases, banks do not provide checks with savings accounts.')
data_entry(1, 'what is current account?','A current account is a bank account that allows you to access a range of banking services, such as receiving money (like your salary, pension or benefits payments), paying bills, and setting up direct debits and standing orders to make regular payments.')
data_entry(2, 'How do I choose the best Savings Account for me? || best savings account for me','Visit your nearest branch and contact financial person there or go to http://sky-bits.com/ for more details.')
data_entry(3, 'what is know your customer? || KYC || What is KYC?','KYC or “Know Your Customer” is a process by which banks obtain information about the identity and address of the customers. This process helps to ensure that bank\'s services are not misused. The KYC procedure is to be completed by the banks while opening accounts and also periodically update the same.')
data_entry(3, 'I want to modify a nominee for my savings account || I want to add a nominee for my savings account || I want to delete a nominee for my savings account','You can add or modify nominee details for your account. Kindly visit your nearest branch and contact branch manager for details.')
data_entry(2, 'benefits for senior citizens savings account || What are the benefits offered by senior citizens savings account?','If you happen to be over 60 years and are still using your old regular savings account, you may be missing out on special features and benefits that can only be availed with senior citizen savings bank account. Here are a few key benefits of switching to a senior citizen savings account: a. higher interest rate for fixed deposits, b. higher withdrawal limit of up to Rs 50,000 per day, c. special medical cards or health cards. Visit your nearest branch or go to http://sky-bits.com/ for more details.')
data_entry(2, 'How can I change my account number? || I want to change my account number','The only way you can have it changed is to close your recent account and open a new one. For futher details, contact your nearest Sky-bits branch.')
data_entry(3, 'What is the rate of interest that I will earn on the balance in my savings Bank Account? || interest rate for my savings account || At what rate will I earn interest on the balance in my Savings Account?','Visit your nearest branch or go to http://sky-bits.com/ for more details.')
data_entry(2, 'I want to link my aadhar number with bank account || How to link my aadhar number with bank account?','If you are an Online Banking customer, you can sign into Online Banking, and Under “My Account” section, click on the “Update Aadhaar with Bank accounts(CIF)” sub-section. Enter profile password for Aadhaar Registration. A page will open where you will be asked to enter your Aadhaar number twice. Click on the “Submit” button after entering your Aadhaar number. A message will be displayed on successful seeding of your Aadhaar. For login got to http://sky-bits.com/. If your are not an Online Banking customer, fill the bank account Aadhaar linking application form. Visit http://sky-bits.com/ to find the ‘Aadhaar-linking’ Form. If not available on the website, please visit your nearest branch. Mention your bank account details as well as your Aadhaar number properly. Attach a self-attested photocopy of your Aadhaar card with the form. Submit the form and the Aadhaar copy at the counter where you may be asked to furnish your original Aadhaar card for verification. Your application will be accepted and it may take a couple of days to link your bank account with Aadhaar. Once linked, you will be notified on your registered mobile number.')
data_entry(3, 'Am I eligible to open a joint account? || I want to open a joint account || Can I open a joint account?','It is very easy to open a joint account. You can apply online or in branch, and each account holder will need to complete an application form with their personal details. Provide proof of address, such as ID card with you.')
data_entry(1, 'Do I need a nominee to open an account?','Nominee details are optional for account holders, such details are updated to ease the payment once the account holder is unable either to operate the account or dies then amount held in such account is paid to the nominee otherwise such amount is being transferred to Govt account for public welfare.')
data_entry(2, 'How can I receive my account statements? || Give me my account statements','If you are an Online Banking customer, you can sign into Online Banking, and select Statements & Documents under the Accounts tab, then go to the Request statements tab and select Order a paper statement copy.For login got to http://sky-bits.com/. Else contact your nearest Sky-bits branch.')
data_entry(1, 'Where should I register my query/complaint?','As a customer, if you have any complaint against your bank, the first step is to contact the bank itself and register a complaint. If you are unable to visit the bank, you can register your complaint here. We will get back to you soon.')
data_entry(1, 'How long will it take to update a change of address?','It usually takes 5 to 6 days to be updated.')