# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script fi"""
import sqlite3
conn=sqlite3.connect('bank-query-sf.db')
c=conn.cursor()
def create_table():
	c.execute("CREATE TABLE IF NOT EXISTS card(no_of_question REAL,query TEXT,answer TEXT)")

def data_entry(a,b,e):
	c.execute("INSERT INTO card VALUES(?,?,?)",(a,b,e))
	conn.commit()
	#c.close()
	#conn.close()

create_table()
data_entry(1,'What happens after I block my card?','Once card is blocked, all features are disabled. For more information contact our customer care or visit your nearest branch for further assistance.')

data_entry(2,'What documents are needed for a new card? ||What documents are needed for a new credit card?','If your application for credit card has been approved online, our executives will contact you within 2 working days to inform about the documents you need to submit. They will also set an appointment with you to collect necessary documents. Once you have submitted your documents, it will take up to 21 working days to process your application. ')

data_entry(47,'I have lost my credit card.||I lost my card.||What to do if I have lost my credit card? ||What to do if I have lost my debit card?  ||Can you tell me the procedure to block credit card?  I have lost it yesterday. ||How to block my card after it is lost or stolen? ||How to block my credit card? ||I can’t find my card.  I am afraid I have lost it. What should I do now? ||My card was stolen yesterday. ||My credit card was stolen yesterday.  ||My card was stolen. What should I do? ||Can I block my card online? Actually I have lost it. ||How can I block my debit card if I have lost it? ||I can’t find my credit card. What should I do? ||Is there any way I can block my debit card? ||Do I need to go to the bank to block my credit card or is there any online method? ||Do I need to go to the bank to block my debit card ?||Can I block my debit card online? ||Within how many days will my debit card be blocked if it is stolen? ||My credit card is damaged. What should I do?||If my card is damaged, how should I replace it?||If my card has a scratch, can I replace my card?||My card is destroyed. I want to block it.||When can I replace my card?||What is the method for card replacement?||I have already got my card replaced once can I do it again?||Is there any replacement fee?||Is replacement of card free of cost?','If your credit card is lost or stolen:You may block the Credit Card through any of the following channels:Internet Banking:My accounts > Credit Cards > Block your Credit card-Instant deactivation> Choose the card number > Submit.Customer Care:You may call our Customer Care from your registered mobile number.Alternatively you can visit your nearest branch with an id proof for further assistance. If your debit card is stolen or lost you may block it immediately by calling our customer care from your registered mobile number or you can visit your nearest branch with an id proof. If your card is damaged or destroyed:Card replacement request can be placed only if destroyed or damaged through :a) Website b) Mobile app .A replacement fee of Rs.100 plus GST (as per current rate) will be applicable.Alternatively, you can call our customer care numbers or visit your nearest branch for further assistance.')
    
data_entry(13,'What is the status of my credit card?||When will I get my credit card?||Within how many days of application, will I get my card?||It has been more than a week, but I haven’t received my credit card yet.||How long do I need to wait for my credit card?||It has been over 5 days and I still haven’t received any updates about my credit card. Where can I get information regarding its status?||How to track my credit card application?||Do I need to go to the bank to enquire about my application?||How to know about the status of my card application.||When will I get my debit card?||It has been 7 days since I have applied for my credit card but I haven’t received it yet. What should I do?||How much time does it take to get debit card after application?||I want to know the status of my application.','Credit card is delivered within 21 working days of submitting your application.If you have applied for a credit card through our website, you can track the status by clicking on "Track Application Status".You will then be asked to enter information such as your application Id, Mobile number, PAN and Date of Birth. If these details match with what we have in our records, you will be able to see the status of your credit card application.If you have applied for a credit card through the branch or any other channels, you can check the status of the application by calling our Customer Care.If you haven’t received within 21 days of submitting your application, or you have concerns regarding application, you can write to us at our customer service website or alternatively, you can visit your nearest branch for further assistance. Debit card is delivered within 7-10 working days after your application is accepted. For further queries, you can contact us through our customer care numbers or write to us. Alternatively, you can visit your nearest branch for further assistance.')

data_entry(8,'How can I get my credit limit increased?||Is there a method to get my credit limit increased?||Can I increase the maximum amount for my credit card?||Why was my credit limit not increased as per request?||What is the method to increase the maximum amount for my credit card?||I want to increase my credit limit.||I had already requested for an increase in my credit limit but it hasn’t been executed yet.||Which documents are required to get my credit limit increased?||Can I increase my credit limit?','The credit limit increase is subject to the bank’s internal risk policy.Please login using your Card username and Password to check your eligibility for increasing your credit limit.If found eligible, the following income documents are required:a) form 16 b) ITR VI c) Last 2 month’s salary slipsThe credit limit increase is subject to the bank’s internal risk policy.Please login using your Card username and Password to check your eligibility for increasing your credit limit.If found eligible, the following income documents are required:a) form 16 b) ITR VI c) Last 2 month’s salary slips')
    
data_entry(6,'What should I do if my credit card got debited for an unknown transaction?||What will I do if I have received an alert for a transaction I didn’t make?||I received a SMS for a transaction which I didn’t make.||What should I do if there is a fraudulent transaction?||What to do if there is a fraudulent transaction through my credit card?||What should I do if my credit card got debited for a transaction I don’t know about?','If you have received an alert for transaction you didn’t make, this may potentially be a fraudulent transaction. Please contact us immediately at our customer care numbers to block your card to avoid further  misuse. Alternatively, you can visit our nearest branch for further assistance.')

data_entry(7,'How to update my mobile number for credit card?||How to update my contact information?||I want to update my address.||I want to update my mobile number and email id.||I want to change my contact details.||I want to fill in my details for credit card.||Can you suggest me a way to update my personal information?','You may update your information in the credit card account by using any of the following options:a) Our bank website b) Mobile app')
    
data_entry(4,'What is the annual fee?||What is the annual fee for my debit card?||I want to know the annual fee for credit card.||What to do if I want to know the annual fee for my debit card?','Annual fee is a one-time charge on your card and renewal fee is charged subsequently every year. To learn more about the fee structure of different cards that we provide, please visit our website or alternatively visit our nearest branch for further assistance')

data_entry(4,'When will my ATM pin be dispatched and how can I track the status of the same?||I haven’t received my credit card pin yet.||When will I get my credit card pin?||How much time does it take to receive ATM pin?','Physical pin is dispatched via speed post. If you haven’t received your credit card pin, you can generate or change the transaction pin for your credit card. You can visit our website for more details or contact us through our customer care numbers. Alternatively you can visit your nearest branch for more assistance.')

data_entry(10,'How can I activate my card?||How to activate card?||Is there a method to activate my card online?||Can I activate my card online?||How do I generate my transaction pin for my credit card?||What to do I have forgotten my pin?||Can you tell me how to update my pin?||I forgot my pin. What should I do now?||I want to generate a new pin.||How can I change my pin?','To activate your card or to update your pin, please login with your username and password. Alternatively, you can write to us or call our customer service. You can also visit your nearest branch for further assistance.If you have forgotten your pin or to generate a new pin, you ca do so by using our website or mobile app. You can also visit your nearest branch for further assistance.')

data_entry(8,'How can I make payment using debit card?||How can I pay my bills using debit card?||How can I do online payment using debit card?||What is the procedure for online payment using debit card?||I want to use my debit card to pay my credit card bills.||How to use debit card to pay credit card bills?||How to use debit card for online payments?||I want to use my debit card for online payments.','You can use your debit card to pay credit card bills or any online payment.a) Select debit card as payment option b) Select the bank whose debit card you wish to use for payment c) Enter card number and CVV d) You will be redirected to the selected bank’s site to complete payment process.For further assistance, you can look at our website or contact us through customer care numbers.')

data_entry(4,'What should I do if my credit card got debited twice?||What should I do if my credit card got debited multiple times?||My credit card got debited thrice for a transaction done only once.||What to do if my credit card got debited twice for a single transaction?','If your card account is debited twice or multiple times for a transaction which was incurred only once, please contact us immediately on our customer care numbers or you can visit your nearest branch. Alternatively, you can write to us at our customer service email id.')

data_entry(12,'Within how many days do I need to pay my credit card bill?||What is the maximum time limit given for the payment of my credit card bill?||How can I get my card statement?||I want to view my statement.||I want to know my payment last date for my credit cardbill.||Where can I view my card statement?||Where can I see my credit card statement?||Is there any payment due date for bill payment?||After receiving my statement, within how many days do I need to pay my bill?||How to view my statement?||How to view my credit card statement? ||What is the maximum amount I can pay using credit card?','You can get the details of your statement by logging using your card username and password. Alternatively, you can get or view it in the following ways:a) A physical statement sent at your registered mailing address.b) A statement on email sent to your registered email address.c) An online statement which can be viewed and downloaded through your online account.Payment due date will be on the 20th day of the statement date. You can view your due date, total amount due, Minimum amount due through our website or mobile app.If you fail to make the payment to your card account on or before the due date, it leads to:a) Levy of additional late payment fees.b) Levy of interest and other charges')
    
data_entry(17,'What is the fastest way to pay my credit card bill?||How to pay my credit card bill?||How do I pay my credit card bill from another bank?||How can I make payment using visa credit card Pay?||When does visa credit card payment reflect in account?||Which is the best way to pay my credit card bill?||What is the procedure to pay for my credit card bill?||I want to pay my bill.||I want to pay my credit card bill.||Which is the easiest way to pay my credit card bill?||which is the best way to pay my bill?||Which is the best way to pay my credit card bill?||Is there a fast and easy way for bill payment?||Within how many days will my bill payment reflect in account?||What are the methods by which I can pay my bill?||Can I use my debit card for bill payment?||When does payment of bill by debit card reflect in account?','To make payment for your card, please login with your Username and password. You can pay using any of the following methods.The following payment methods are instant.a) Pay via mobile app b) Pay through our online website.c) Electronic bill payment.d) Debit card Other methods like:a) Visa credit card pay – 3 days b) Manual drop box(3-5 working days) c) Electronic drop box(3-5 working days)d) ATM( 2 working days).For more payment related queries visit our website or nearest branch.Alternatively you can call our customer care for further assistance.')

data_entry(36,'How can I apply for a new credit card? ||How can I apply for a new debit card? ||I want a new card.||What are the different types of card available? ||I want to apply for a new card. ||I want to apply for a new debit card.||Can you please tell me what should I do to apply for a new card?|| Can you please tell me what should I do to apply for a new credit card? ||Can you please tell me what should I do to apply for a new debit card? ||What are the prerequisites for applying for a new credit card? ||Do I need to have an account to apply for a new card? ||What is the procedure to apply for a new card?||I have a query regarding the procedure to apply for a new debit card. ||How to get a new credit card? ||How to get a new debit card? ||I want a new card.||Are there any other types of card other than credit card?|| Are there any charges imposed if we apply for a new credit card?|| Are there any charges imposed if we apply for a new debit card?|| What is the annual charge incurred if I take a credit card?|| What is the annual charge incurred if I take a debit card?|| Is debit card free of any cost?|| Is credit card free of any cost?|| What are the different types of cards? || Which type of card will be most beneficial for me? ||Can I apply for a card online? ||Can I apply for a credit card online?|| Is there any criteria to apply for a new card? ||Can you tell me how to apply for a credit card?||Can you tell me how to apply for a debit card?||Is credit card free?||Do you have any free card?||What are the charges imposed by credit card?||Is there a free credit card?||Is there a free card?','To apply for a Debit Card:We request you to apply for a new Debit Card through any of the below mentioned channels:Internet Banking:Please login to our website > Login > Customer Service > Service Requests > Reissue of Lost ATM/Debit Card. Click here to reissue debit card.Customer Care:We request you to call our Customer Care between 7:00 a.m. and 9:00 p.m. from your registered mobile number. Nearest bank branch:Please visit the nearest branch with your valid ID proof.Once the request is placed, the card will be delivered within 10 working days at your communication address updated in our records. The existing Debit Card will be blocked once the new card is delivered. Credit card:We have a variety of credit cards to suit your needs. But, we do not offer free cards. All of them come with a cost, but there are welcome benefits associated with each. (To know more regarding benefits visit website)1) Maximum rewards2) Flight/Air miles3) Fuel cashback4) Lifetime free card5) Customizable look6) Ferrari fan To know more visit the bank website. You can also apply now. Alternatively, you can visit the nearest branch for further assistance.')    
    
    